zviadm/celoterminal

- src/lib/utils.ts
- src/renderer/apps/celovote/celovote.tsx
- src/renderer/apps/locker/locker.tsx
- src/renderer/coreapp/tx-runner/tx-runner.tsx
* fixes to TX-Runner to handle safely running multiple transactions
> [app/locker] implement revoke and unlock

- src/lib/accountsdb.ts
- src/lib/error.ts
- src/lib/utils.ts
- src/renderer/apps/celovote/celovote.tsx
- src/renderer/apps/locker/locker.tsx
- src/renderer/apps/send-receive/send-receive.tsx
- src/renderer/components/app-definition.ts
- src/renderer/coreapp/accounts-app/accounts-app.tsx
- src/renderer/coreapp/accounts-app/addressonly-account.tsx
- src/renderer/coreapp/accounts-app/change-password.tsx
- src/renderer/coreapp/accounts-app/create-local-account.tsx
- src/renderer/coreapp/accounts-app/import-local-account.tsx
- src/renderer/coreapp/accounts-app/ledger-account.tsx
- src/renderer/coreapp/accounts-app/reveal-local-key.tsx
- src/renderer/coreapp/accounts-bar.tsx
- src/renderer/coreapp/app.tsx
- src/renderer/coreapp/appstore-app/appstore-app.tsx
- src/renderer/coreapp/ledger-utils.ts
- src/renderer/coreapp/tx-runner/tx-runner.tsx
- src/renderer/coreapp/tx-runner/wallet.ts
- src/renderer/state/error-context.tsx
- src/renderer/state/onchain-state.ts
* use React.useCallback for memoizing to make sure hook dependency linter still works
* create global ErrorContext/Provider that handles all uncaught exceptions
> [core] cleanup useOnChainState and overall error handling

- src/renderer/apps/send-receive/send-receive.tsx
- src/renderer/components/address-autocomplete.tsx
> [app/send-receive] factor out address-autocomplete as a separate component

- buildcfg/build.js
- src/renderer/coreapp/accounts-bar.tsx
- src/renderer/coreapp/network-indicator.tsx
* move NetworkIndicator as a separate component
* only check blockNumber for network status
> [core] only check blockNumber for network status

- src/renderer/apps/governance/governance.tsx
handle vote signer more correctly.
> [app/governance] fetch voting data for main account

- package.json
- src/lib/spectron-utils/app-helpers.ts
- src/lib/spectron-utils/devchain-helpers.ts
- src/renderer/apps/governance/governance.tsx
- src/renderer/apps/governance/spectron-tests/governance.test.ts
- src/renderer/apps/locker/spectron-tests/locker.test.ts
- src/renderer/apps/send-receive/spectron-tests/send-receive.test.ts
- src/renderer/coreapp/tx-runner/tx-runner.tsx
- yarn.lock
* confirmTX helper automatically knows when to enter password
* wait for data refetch after confirmTX call is made
* remove unnecessary extra delay in TXRunner preparation stage
* fix governance upvoting (when revoke is needed)
* filter out expired dequeued governance proposals
> [app/governance] add tests for governance app and fix little issues

- src/renderer/coreapp/network-indicator.tsx
Better error message when connect fails. Include last block information when syncing is not up to date.
Fixes: #65
> [core] improve network indicator messaging

- src/lib/utils.ts
- src/renderer/apps/locker/locker.tsx
- src/renderer/apps/mento/mento.tsx
- src/renderer/apps/send-receive/send-receive.tsx
- src/renderer/components/address-autocomplete.tsx
- src/renderer/components/number-input.tsx
TextField slight stylistic changes and a shared NumberInput element.
> [app/locker] add 'max' button for unlocking

- src/lib/utils.test.ts
- src/lib/utils.ts
* also adjust precision for values close to zero more dynamically
> [core] round down amounts

- src/lib/erc20/core.ts
- src/lib/erc20/erc20-contract.ts
- src/lib/erc20/registry-alfajores.ts
- src/lib/erc20/registry-baklava.ts
- src/lib/erc20/registry-devchain.ts
- src/lib/erc20/registry-mainnet.ts
- src/lib/erc20/registry.test.ts
- src/lib/registry.ts
- src/lib/utils.test.ts
- src/lib/utils.ts
- src/renderer/apps/apps.ts
- src/renderer/apps/portfolio/balances.ts
- src/renderer/apps/portfolio/def.ts
- src/renderer/apps/portfolio/portfolio.tsx
- src/renderer/apps/portfolio/spectron-tests/portfolio.test.ts
- src/renderer/apps/send-receive/send-receive.tsx
- src/renderer/apps/send-receive/spectron-tests/send-receive.test.ts
- src/renderer/apps/send-receive/transfer-history.tsx
- src/renderer/components/add-erc20.tsx
- src/renderer/components/number-input.tsx
- src/renderer/state/erc20list-state.ts
app/portfolio: to show total balances
> [core/erc20] remove fullName and use combination of name & symbol

- src/lib/tx-parser/contract-abi.ts
- src/renderer/apps/sc-inspector/sc-inspector.tsx
- src/renderer/apps/sc-inspector/spectron-tests/sc-inspector.test.ts
> [app/sc-inspector] allow entering lower-case addresses

- package.json
- src/renderer/apps/apps.ts
> [app/wc] remove wallet-connect app once again

- package.json
- src/renderer/apps/apps.ts
* Memory leak issues aren't reproducible. Seems like everything is working fine.
> [app/wc] re-enable wallet connect in Beta

- src/renderer/components/select-erc20.tsx
- src/renderer/state/erc20list-state.ts
- yarn.lock
* plus update default token list for OpticsV2 support
> [core/erc20s] fix handling of confliciting erc20 symbols

- package.json
- src/lib/erc20/core.ts
- yarn.lock
~Not passing tests -- I believe savingscelo's contractkit dependency has to be in sync.~
Addressed by [f37a8122b60d333f20d9d5aa92f2897d1890a0cb](https://github.com/zviadm/celoterminal/commit/f37a8122b60d333f20d9d5aa92f2897d1890a0cb).
> Add cREAL support.

- src/renderer/apps/moola/governance/details.tsx
- src/renderer/apps/moola/governance/index.tsx
- src/renderer/apps/moola/governance/proposals.tsx
- src/renderer/apps/moola/moola-helper.tsx
- src/renderer/apps/moola/moola.tsx
Update Moola governance integration, add abilities to:
- change delegate address
- queue a proposal when in "Succeeded" state 
- execute a proposal in "Queued" state after eta has passed
> Moola | Add delegate, queue and execute actions for governance

- package.json
- src/renderer/apps/mento/state.ts
- src/renderer/apps/savingscelo/history-state.ts
- src/renderer/apps/send-receive/send-receive.tsx
- src/renderer/apps/swappa/state.ts
- src/renderer/state/event-history-state.ts
- yarn.lock
* update swappa with its initialization improvements
* smarter progressive fetch batch sizing based on fetch times
* reduce history sizes for recent events due to huge slow down of event fetching
> [app/swappa] update swappa to latest version to speed up initialization

- src/renderer/state/error-context.tsx
> wc: try adding more helpful error messsage when walletconnect has issues

- src/renderer/apps/send-receive/send-receive.tsx
- src/renderer/apps/send-receive/transfer-from-tab.tsx
this should fix #354 
chain is now way too slow to actually retrieve all approval/spender information so allow entering custom addresses for transferFrom operations.
> [send-receive] allow entering custom addresses in transferFrom

- src/lib/fee-tokens.ts
- src/renderer/apps/wallet-connect/v2/wc.ts
- src/renderer/coreapp/network-indicator.tsx
- src/renderer/coreapp/tx-runner/fee-estimation.ts
- src/renderer/coreapp/tx-runner/run-txs.tsx
- src/renderer/coreapp/tx-runner/wallet.ts
Automatically selects custom Gas token if there isn't enough CELO balance
> [core] add support for automatically selecting custom Gas tokens
